### ISSUE TITLE
缺少model文件

### ISSUE THREAD

**Issue by DUTXT** [zyDotwei/humor_computation#1]
请问方不方便补充一下model文件啊，缺了'sequence_bert'和'sequence_with_speaker_bert'

**Comment by zyDotwei** [comment]
你好，都在model/bert.py文件中。

**Comment by DUTXT** [comment]
嗯嗯   bert.py中有SequenceBert类，但是没有看到sequence_with_speaker_bert

**Comment by zyDotwei** [comment]
就没有这个类，这只是个配置参数出现在配置文件和run文件中。

**Comment by DUTXT** [comment]
原来如此，是我还没看明白，多谢多谢

**Comment by zyDotwei** [comment]
sequence_with_speaker_bert这个的效果不太好，就没有放出来哈

**Comment by DUTXT** [comment]
ok
